# Generated by Django 4.2.2 on 2023-06-26 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('rut', models.CharField(max_length=9)),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=60)),
                ('contraseña', models.CharField(max_length=100)),
                ('suscripcion', models.BooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagenUrl',
            field=models.ImageField(upload_to='media/imagenesProducto'),
        ),
    ]
